### ISSUE TITLE
Possible PR

### ISSUE THREAD

**Issue by philipturner** [AIprogrammer/Awesome-Monocular-3D#1]
I have a research paper on [adding color to scene reconstruction](https://github.com/philipturner/scene-color-reconstruction) that just got rejected from openMVG/awesome_3DReconstruction_list. Would mine qualify for this repository?

**Comment by annopackage** [comment]
Hi, this repo is still under construction, and you are free to submit a PR.

**Comment by philipturner** [comment]
PR submitted

**Comment by philipturner** [comment]
Thank you so much!
